<a href="https://colab.research.google.com/github/saiprathyushadike/ML_DL_MODELS_IMPLIMENTATION_BY_ME/blob/main/hoe3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EXAMPLE - 3.1

In [1]:
r = 3.35
h=4.16

In [2]:
import math
volume = round(math.pi * pow(r, 2) * h, 3)
volume

146.667

In [3]:
area = round(2 * math.pi * r**2 + 2 * math.pi * r * h, 3)

In [4]:
area

158.076

EXAMPLE 3.2

In [8]:
import math

for n in range(50, 56):
  k = 4
  print(f"n={n}, k={k}")
  print(math.comb(n, k))

  comb = math.factorial(n) // (math.factorial(k) * math.factorial(n-k))
  print(comb)
  print("-" * 20)

n=50, k=4
230300
230300
--------------------
n=51, k=4
249900
249900
--------------------
n=52, k=4
270725
270725
--------------------
n=53, k=4
292825
292825
--------------------
n=54, k=4
316251
316251
--------------------
n=55, k=4
341055
341055
--------------------


In [9]:
for i in range(50,56):
  r = math.comb(n,4) == math.factorial(n) // (math.factorial(4) * math.factorial(n-4))
  print(r)

True
True
True
True
True
True


In [13]:
import math

def mycomb(n, k):
  return math.factorial(n) / math.factorial(k) / math.factorial(n - k)

In [12]:
import math

for n in range(50, 56):
    r1 = math.comb(n, 4)
    r2 = mycomb(n, 4)
    print(f'{r1}, {r2}, {r1 == r2}')

230300, 230300.0, True
249900, 249900.0, True
270725, 270725.0, True
292825, 292825.0, True
316251, 316251.0, True
341055, 341055.0, True


In [14]:
import numpy as np
print(np.zeros(5))
print()
print(np.zeros((3,4)))

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
print(np.ones((3,4,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [17]:
x = [
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]
    ],
    [
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]
    ]
]

print(np.array(x))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


EXAMPLE 3.4

In [19]:

arr = np.arange(24).reshape(2, 3, 4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [20]:
flat = arr.flatten()

In [21]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
flat1 = arr.reshape(-1)

In [25]:
flat1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

EXAMPLE 3.5

In [26]:
x = np.arange(0,24)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [28]:
x = x.reshape((4,-1))
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [30]:
print(x[1:3, :])

[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [32]:
print(x[:,-2:])

[[ 4  5]
 [10 11]
 [16 17]
 [22 23]]


EXAMPLE 3.7

In [33]:
arr = np.arange(0, 47, 2).reshape(4, 6)
print(arr)

[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]


In [37]:
y = (x/5) /(x//5)

/tmp/ipython-input-4030175863.py:1: RuntimeWarning: divide by zero encountered in divide
  y = (x/5) /(x//5)
/tmp/ipython-input-4030175863.py:1: RuntimeWarning: invalid value encountered in divide
  y = (x/5) /(x//5)


In [38]:
y

array([[       nan,        inf,        inf,        inf,        inf,
        1.        ],
       [1.2       , 1.4       , 1.6       , 1.8       , 1.        ,
        1.1       ],
       [1.2       , 1.3       , 1.4       , 1.        , 1.06666667,
        1.13333333],
       [1.2       , 1.26666667, 1.        , 1.05      , 1.1       ,
        1.15      ]])

In [39]:
np.all(y > 0)

np.False_

In [43]:
np.any(np.isnan(y))

np.True_

In [41]:
print(y>0)

[[False  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [44]:
np.isinf(y)

array([[False,  True,  True,  True,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [45]:
np.any(np.isinf(y))

np.True_

example 3.9

In [46]:
x = np.array([
    [6, 6, 3, 9],
    [0, 5, 2, 0],
    [2, 1, 4, 8]
])

In [ ]:
minimum = np.min(x)
print(minimum)
maximum = np.max(x)
print(maximum)
mean = np.mean(x)
print(mean)